### ISSUE TITLE
inline code string values rendering as unicode python, eg u'some string' instead of 

### ISSUE THREAD

**Issue by thatcher** [jankatins/knitpy#27]
In a .pymd this is the mark up

```
My name is `python my_name`
```

renders as

`My name is u'Chris'`

instead of

`My name is Chris`

**Comment by JanSchulz** [comment]
I'm not sure that there is an easy fix here :-( The code behind this is basically the same as writing this in a cell in the notebook:

```
In [5]: u"üä"
Out[5]: u'\xfc\xe4'
```

So, if the above inline code should return the string *without* quotes (and as a normal "readable" unicode instead of encoded ones) but in code blocks this should show quotes and `u"..."` signs... this needs a switch in the plain text formatter before/after each submitted code (or at least when switching from inline to block and reverse :-/ 

```
from IPython.core.interactiveshell import InteractiveShell
shell = InteractiveShell.instance()
tp = shell.display_formatter.formatters[u'text/plain']
# then set the following to some functions which does the same as `print`  
tp.type_printers[unicode] # and str
```

Not sure if there are any better alternatives...

**Comment by JanSchulz** [comment]
Or the easier way: add a small wrapper in the engine code which does this for you:

So instead of submitting `my_name` it's submitting `p.text(my_name)` to be executed...
